export default {
  BASE_URL: process.env.NEXT_PUBLIC_API_URL,
  user_reducer: {
    LOGIN_USER: "LOGIN_USER",
    LOGOUT_USER: "LOGOUT_USER",
    UPDATE_EMAIL: "UPDATE_EMAIL",
    UPDATE_USER_PROFILE: "UPDATE_USER_PROFILE"
  },
  item_type: {
    FILTER_ITEM_SORT_BY: "FILTER_ITEM_SORT_BY",
    ORDER_ITEM_BY_PRICE: "ORDER_PRODUCTS_BY_PRICE",
    FETCH_ITEMS: "FETCH_ITEMS"
  },
  cart: {
    FETCH_TO_CART: "FETCH_TO_CART",
    ADD_TO_CART: "ADD_TO_CART",
    QUICK_BUY_PRICE: "QUICK_BUY_PRICE",
    REMOVE_FROM_CART: "REMOVE_FROM_CART",
    REMOVE_ITEM: "REMOVE_ITEM",
    SUB_QUANTITY: "SUB_QUANTITY",
    ADD_QUANTITY: "ADD_QUANTITY",
    ADD_SHIPPING: "ADD_SHIPPING",
    INCREMENT: "INCREMENT",
    DECREMENT: "DECREMENT",
    RESET: "RESET",
  },
  others: {
    CHANGE_LOCALE: "CHANGE_LOCALE",
    SET_UI_TRANSLATIONS_LOADING: "SET_UI_TRANSLATIONS_LOADING",
    SET_UI_TRANSLATIONS_LOADED: "SET_UI_TRANSLATIONS_LOADED"
  },
  menusItem: {
    MEGAMENU: "MEGAMENU",
    MID_SECTION: "MID_SECTION",
    TOPBAR_SECTION: "TOPBAR_SECTION"
  }
};



